### PR TITLE
Kenny

### PR DESCRIPTION
**Pull request by Nandob777**
Kenny is an exec, and he deserves to be on the site.  This adds him and arranges the execs in a hexagon

### CODE REVIEW

**Comment by ratstache** [comment]
it looks like when you made this branch you did it from the favicon branch so those commits were still there. We also want to get rid of the "Merge branch 'master'" commit. When you are rebasing just skip the first three and only add a1bffd108436bf54cee7339f75f2c9394435fcae.

**Comment by Nandob777** [comment]
I actually thought I was on my fork, and tbh I almost pushed to master. 
@kerosenecity is there a way to disable pushing directly to branches on this repo, and instead limit it to pr's  from other forks?

**Comment by Nandob777** [comment]
@kerosenecity something like [Protected branches](https://help.github.com/articles/about-protected-branches/) might be a solution.  I'll make an issue with this

**Comment by ratstache** [comment]
yeah, make the issue, I'm setting it up right now.

**Comment by Nandob777** [comment]
I just saw the automatic merge pull request button disappear, and I paniced and thought I used a keyword I shouldn't have

**Comment by ratstache** [comment]
closing because #33 has replaced it.

**Pull request closed without merging**
